# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: OSS Webinar 3 Python Tutorial
author: Kevin Anderson, Matt Prilliman
#logo: images/tutorial_banner.PNG
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, venv, .git, .github, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files: false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PV-Tutorials/2024_Analytics_Webinar
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  thebe: true
  colab_url: "https://colab.research.google.com"
